apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: encrypted
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: engineers2526@gmail.com
    privateKeySecretRef:
      name: encrypted
    solvers:
      - http01:
          ingress:
            class: nginx